# Generated by Django 4.0.3 on 2022-03-29 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_halftime_goal', models.IntegerField(default=0)),
                ('away_team_halftime_goal', models.IntegerField(default=0)),
                ('home_team_goal', models.IntegerField(default=0)),
                ('away_team_goal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatchStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_play', models.IntegerField()),
                ('set_piece', models.IntegerField(default=0)),
                ('counter_attack', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('own_goal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goal_for', models.IntegerField(default=0)),
                ('goal_against', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('logo_url', models.ImageField(upload_to='images')),
                ('away_statistic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_statistic', to='PremierLeague.teamstatistic')),
                ('home_statistic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_statistic', to='PremierLeague.teamstatistic')),
                ('overall_statistic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overall_statistic', to='PremierLeague.teamstatistic')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='PremierLeague.team')),
                ('away_team_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_statistic', to='PremierLeague.matchstatistic')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='PremierLeague.team')),
                ('home_team_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_statistic', to='PremierLeague.matchstatistic')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PremierLeague.matchresult')),
            ],
        ),
    ]
