# Generated by Django 4.0.3 on 2022-03-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PremierLeague', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.ImageField(upload_to='media'),
        ),
    ]
